### ISSUE TITLE
Sometimes angle rotated is incorrect

### ISSUE THREAD

**Issue by jishh** [doublerobotics/Basic-Control-SDK-iOS#3]
I have used "turnByDegrees" function to rotate by 90 degrees after a forward walk. But sometimes the robot do a small tilt and 90-degree rotation is incorrect. Is this a behaviour in uneven (non-flat) surfaces, if so can I calculate the angle effectively rotated and force rotation to desire values?

**Comment by davidcann** [comment]
That's correct – turn by degrees is not always accurate, especially at larger angles. You can probably get more accurate turning in place by turning slower and reading the travel data heading.

**Comment by jishh** [comment]
Thanks for the reply. Is there a way to get a callback for the function "turnByDegrees", for knowing when rotation ended.

**Comment by davidcann** [comment]
There is no callback at the end of turnByDegrees. If you need more precise control, you should implement your own feedback loop.
